### ISSUE TITLE
[feat] Add ability to add non-free software (namely for DIY wi-fi)

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/start-os#2078]
PureOS (Rightly) does not include any proprietary hardware blobs.  This is going to be a problem for many users that attempt to use Wi-Fi on DIY hardware.  Suggestion is to add the ability (under the Wi-Fi tab) to add `non-free` and `contrib` repos to /etc/apt/sources.list - if applicable.  This seems to be how Ubuntu generally supports a wide array of wi-fi cards.

**Comment by gStart9** [comment]
AFAIUI this is solved (as of v0.3.4) by:

```
sudo /usr/lib/embassy/scripts/chroot-and-upgrade
apt update
apt install firmware-ath9k-htc
exit
```
Where `firmware-ath9k-htc` is the firmware package from any pureos or debian repo (including non-free) you want

**Comment by kn0wmad** [comment]
There will actually be builds that allow (and builds that do not allow) non-free software.  Some default software will also likely be included for upcoming s9 hardware and commonly needed DIY drivers.

**Comment by kn0wmad** [comment]
This is closed by v0.3.4.2

**Comment by z3ke-sk1** [comment]
> This is closed by v0.3.4.2

I was the reason why this was opened. It is still not working.
